### PR TITLE
Pushes for /index.html work when surfing to /

### LINKED ISSUE #1744: Push not working when surfing to website root
### 1. What version of Caddy are you using (`caddy -version`)?
Compiled from master branch
(I am using the latest Chromium).

### 2. What are you trying to do?
I'm trying to push resources when a client browses to the homepage. However nothing is pushed when surfing to https://foo.bar, only when surfing explicitly to https://foo.bar/index.html

### 3. What is your entire Caddyfile?
```text
https://thesis_server.be:6121
root ./website
tls ./website/cert.crt ./website/cert.key
push /index.html {
    /dash.all.debug.js
    /thesis.js
    /video/2000/manifest.mpd
    /video/2000/240/segment_init_240.mp4
    /video/2000/240/segment_0000_240.mp4
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`./caddy -http2=true -log stdout`

### 5. Please paste any relevant HTTP request(s) here.
For this request nothing is pushed:
```
Frame 65: 342 bytes on wire (2736 bits), 342 bytes captured (2736 bits) on interface 0
Ethernet II, Src: 00:00:00_00:00:00 (00:00:00:00:00:00), Dst: 00:00:00_00:00:00 (00:00:00:00:00:00)
Internet Protocol Version 4, Src: localhost (127.0.0.1), Dst: localhost (127.0.0.1)
Transmission Control Protocol, Src Port: 32808, Dst Port: 6121, Seq: 487, Ack: 1679, Len: 276
Secure Sockets Layer
HyperText Transfer Protocol 2
    Stream: HEADERS, Stream ID: 1, Length 238
        Length: 238
        Type: HEADERS (1)
        Flags: 0x25
        0... .... .... .... .... .... .... .... = Reserved: 0x0
        .000 0000 0000 0000 0000 0000 0000 0001 = Stream Identifier: 1
        [Pad Length: 0]
        1... .... .... .... .... .... .... .... = Exclusive: True
        .000 0000 0000 0000 0000 0000 0000 0000 = Stream Dependency: 0
        Weight: 255
        [Weight real: 256]
        Header Block Fragment: 82418b4ce54191120b6772d8bc6587844092b6b9ac1c8558...
        [Header Length: 444]
        [Header Count: 9]
        Header: :method: GET
        Header: :authority: thesis_server.be
        Header: :scheme: https
        Header: :path: /
        Header: upgrade-insecure-requests: 1
        Header: user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/58.0.3029.110 Chrome/58.0.3029.110 Safari/537.36
        Header: accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
        Header: accept-encoding: gzip, deflate, sdch, br
        Header: accept-language: en-US,en;q=0.8
        Padding: <MISSING>
```

For this request, the relevant resources are pushed:
```
Frame 70: 342 bytes on wire (2736 bits), 342 bytes captured (2736 bits) on interface 0
Ethernet II, Src: 00:00:00_00:00:00 (00:00:00:00:00:00), Dst: 00:00:00_00:00:00 (00:00:00:00:00:00)
Internet Protocol Version 4, Src: localhost (127.0.0.1), Dst: localhost (127.0.0.1)
Transmission Control Protocol, Src Port: 60928, Dst Port: 6121, Seq: 487, Ack: 1717, Len: 276
Secure Sockets Layer
HyperText Transfer Protocol 2
    Stream: HEADERS, Stream ID: 1, Length 238
        Length: 238
        Type: HEADERS (1)
        Flags: 0x25
        0... .... .... .... .... .... .... .... = Reserved: 0x0
        .000 0000 0000 0000 0000 0000 0000 0001 = Stream Identifier: 1
        [Pad Length: 0]
        1... .... .... .... .... .... .... .... = Exclusive: True
        .000 0000 0000 0000 0000 0000 0000 0000 = Stream Dependency: 0
        Weight: 255
        [Weight real: 256]
        Header Block Fragment: 82418b4ce54191120b6772d8bc6587854092b6b9ac1c8558...
        [Header Length: 454]
        [Header Count: 9]
        Header: :method: GET
        Header: :authority: thesis_server.be
        Header: :scheme: https
        Header: :path: /index.html
        Header: upgrade-insecure-requests: 1
        Header: user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/58.0.3029.110 Chrome/58.0.3029.110 Safari/537.36
        Header: accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
        Header: accept-encoding: gzip, deflate, sdch, br
        Header: accept-language: en-US,en;q=0.8
        Padding: <MISSING>
```
### 6. What did you expect to see?
I expected Caddy to push the 5 resources specified for /index.html.

### 7. What did you see instead (give full error messages and/or log)?
Nothing was pushed wheb surfing to https://foo.bar
 (I have wireshark logs).

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Try to push a resource for /index.html while surfing to the website (not foo.bar/index.html)

### PR DESCRIPTION
**Pull request by twdkeule**
### 1. What does this change do, exactly?
Send the push resources for `/index.html` when requesting the root/home page `/`

### 2. Please link to the relevant issues.
Fix #1744 

### 3. Which documentation changes (if any) need to be made because of this PR?
None

### 4. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

**Comment by magikstm** [comment]
It should probably use values of that directive instead of being hardcoded: https://caddyserver.com/docs/index

File: caddyhttp/push/handler.go [hunk 1]
```diff
@@ -25,7 +25,9 @@ func (h Middleware) ServeHTTP(w http.ResponseWriter, r *http.Request) (int, erro
 	// push first
 outer:
 	for _, rule := range h.Rules {
-		if httpserver.Path(r.URL.Path).Matches(rule.Path) {
+		path := r.URL.Path
+		if httpserver.Path(path).Matches(rule.Path) ||
+			(rule.Path == "/index.html" && path == "/") {
```
Comment (mholt) [inline caddyhttp/push/handler.go]: I agree with @magikstm; this should refer to `staticfiles.IndexPages`.

**Comment by twdkeule** [comment]
However, what if someone wants to specify different push resources for different IndexPages?

**Comment by tobya** [comment]
LGTM

**Comment by twdkeule** [comment]
Should I squash the commits?

File: caddyhttp/push/handler_test.go [hunk 2]
```diff
@@ -307,6 +308,58 @@ func TestMiddlewareShouldInterceptLinkHeaderPusherError(t *testing.T) {
...
 
+func TestMiddlewareShouldPushIndexFile(t *testing.T) {
+	// given
+	indexFile := "/index.html"
+	request, err := http.NewRequest(http.MethodGet, "/", nil) // Request root directory, not indexfile itself
+	if err != nil {
+		t.Fatalf("Could not create HTTP request: %v", err)
+	}
+
+	root := "."
```
Comment (mholt) [inline caddyhttp/push/handler_test.go]: Let's use a temporary folder instead. See ioutil.TempDir for an easy way to do this.

File: caddyhttp/push/handler_test.go [hunk 3]
```diff
@@ -307,6 +308,58 @@ func TestMiddlewareShouldInterceptLinkHeaderPusherError(t *testing.T) {
...
+		}),
+		Rules: []Rule{
+			{Path: indexFile, Resources: []Resource{
+				{Path: "/index.css", Method: http.MethodGet},
+			}},
+		},
+		Root: http.Dir(root),
+	}
+
+	_, err = os.Create(root + indexFile)
```
Comment (mholt) [inline caddyhttp/push/handler_test.go]: Use filepath.Join to ensure cross-platform compatibility, instead of straight concatenation.

File: caddyhttp/push/handler_test.go [hunk 4]
```diff
@@ -307,6 +308,58 @@ func TestMiddlewareShouldInterceptLinkHeaderPusherError(t *testing.T) {
...
+	if err != nil {
+		t.Fatalf("Could not create index file: %s: %v", indexFile, err)
+	}
+	defer os.Remove(root + indexFile)
```
Comment (mholt) [inline caddyhttp/push/handler_test.go]: Same, use filepath.Join

File: caddyhttp/push/setup.go [hunk 5]
```diff
@@ -34,8 +34,9 @@ func setup(c *caddy.Controller) error {
 		return err
 	}
 
-	httpserver.GetConfig(c).AddMiddleware(func(next httpserver.Handler) httpserver.Handler {
-		return Middleware{Next: next, Rules: rules}
+	cfg := httpserver.GetConfig(c)
+	cfg.AddMiddleware(func(next httpserver.Handler) httpserver.Handler {
+		return Middleware{Next: next, Rules: rules, Root: http.Dir(cfg.Root)}
```
Comment (mholt) [inline caddyhttp/push/setup.go]: Excellent that you're using http.Dir

**Comment by twdkeule** [comment]
I also fixed issue #1776 in the last commit. It was easier than expected.

**Comment by mholt** [comment]
@twdkeule Cool, thanks - almost there. But regarding pushing after sending the initial request, how does your latest commit (for #1776) relate to this: https://github.com/mholt/caddy/pull/1215#discussion_r101894949

**Comment by twdkeule** [comment]
Indeed, I missed something. 
The push_promise should be sent before the response to the initial request. The pushed data does not have to be sent first.
But the way HTTP2 is implemented in go, the pushed data will always be sent right after the push_promise. So the problem is not part of Caddy.
I will revert and  squash the last commit

**Comment by mholt** [comment]
Excellent!! Thanks, @twdkeule.

I'll invite you to be a Collaborator to the project, so in the future you can make patches in a branch, not a fork, and also will have power to help review pull requests and issues, etc. Really appreciate your improvements!

File: caddyhttp/push/handler.go [hunk 6]
```diff
@@ -25,7 +26,13 @@ func (h Middleware) ServeHTTP(w http.ResponseWriter, r *http.Request) (int, erro
 	// push first
 outer:
 	for _, rule := range h.Rules {
-		if httpserver.Path(r.URL.Path).Matches(rule.Path) {
+		urlPath := r.URL.Path
+		matches := httpserver.Path(urlPath).Matches(rule.Path)
+		// Also check IndexPages when requesting a directory
+		if !matches {
+			_, matches = httpserver.IndexFile(h.Root, urlPath, staticfiles.IndexPages)
```
Comment (twdkeule) [inline caddyhttp/push/handler.go]: This does not check whether or not the index file actually matches a push rule -> #1809

Comment (mholt) [inline caddyhttp/push/handler.go]: Ahh, yeah, duh, how did we miss that. We should add a test case to check for this. :)
