### PR TITLE
Fix rewrite bug with URL query + test case (#884)

### LINKED ISSUE #884: rewrite bug with URL query
#### 1. What version of Caddy are you running (`caddy -version`)?
0.9 (master)

#### 2. What are you trying to do?
Use `rewrite` directive with URL on query
 
#### 3. What is your entire Caddyfile?
```text
0.0.0.0:2015
rewrite {
    r (.*)
    to /proxy/{path}?{query}
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
`go run main.go`

#### 5. What did you expect to see?
Caddy should rewrite any URL without changing the query.

Example:
```
/example?url=http://caddyserver.com -> /proxy/example?url=http://caddyserver.com
```

#### 6. What did you see instead (give full error messages and/or log)?
Caddy is removing a `/` from the query.

Example
```
/example?url=http://caddyserver.com -> /proxy/example?url=http:/caddyserver.com
```
#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Just use the caddyfile

### PR DESCRIPTION
**Pull request by pedronasser**
Prevent `rewrite.To()` method to use `path.Clean()` on URL's query.
Closes #884.

### CODE REVIEW

**Comment by guilhermebr** [comment]
:+1

File: caddyhttp/rewrite/to.go [hunk 1]
```diff
@@ -18,8 +18,15 @@ func To(fs http.FileSystem, r *http.Request, to string, replacer httpserver.Repl
 
 	// try each rewrite paths
 	t := ""
+	query := ""
 	for _, v := range tos {
-		t = path.Clean(replacer.Replace(v))
+		t = replacer.Replace(v)
+		tparts := strings.Split(t, "?")
```
Comment (mholt) [inline caddyhttp/rewrite/to.go]: Is this a safe way to split the URL?

Comment (pedronasser) [inline caddyhttp/rewrite/to.go]: Not really sure? I think more about possible cases and other solution to get the query.
And we can't really use url.Parse() to solve that problem.

Comment (mholt) [inline caddyhttp/rewrite/to.go]: Hmm, well I like the simplicity of your PR as-is, I'll look at this again tomorrow after I've had some sleep and try to think of ways to break it. In the meantime it looks like this is easy enough to test as you've shown, so we can always add those later if they come up.

**Comment by abiosoft** [comment]
Well, I am not in favour of this. if you really want to use that url, then escape it.

`path.Clean` cleans up the url and prevents accessing parent directories.

File: caddyhttp/rewrite/to.go (hunk 1 above)
Comment (abiosoft) [inline caddyhttp/rewrite/to.go]: why not `tparts := strings.SplitN(t, "?", 2)` ?

**Comment by abiosoft** [comment]
Your description was a bit misleading. I thought you removed `path.Clean` in its entirety.
> Prevent rewrite.To() method to use path.Clean() on URL's query.

**Comment by abiosoft** [comment]
This is why we provided `{path_escaped}`, `{uri_escaped}`, `{query_escaped}` placeholders. Though it did not occur to me users may need to put in their own urls.

There was once a similar issue but caused by regex and was handled here.
https://github.com/mholt/caddy/blob/master/caddyhttp/rewrite/rewrite.go#L171.

File: caddyhttp/rewrite/to.go (hunk 1 above)
Comment (pedronasser) [inline caddyhttp/rewrite/to.go]: Agreed. SplitN is better in this case. I'll replace it.
