### PR TITLE
Parse address from fastcgi directive, pass results to Dial()

### LINKED ISSUE #540: Allow for scheme prefix before fastcgi server's IP address
My Caddyfile has the following directive

```
fastcgi / {$PHP_URL} php
```

The env var `PHP_URL` equates to `tcp://172.17.0.1:9000` and is set by my Docker setup. It appears Caddy does not support any sort of scheme prefix before the IP address and fails with the following error:

```
27/Jan/2016:17:04:40 +0000 [ERROR 502 /index.php] dial tcp: too many colons in address tcp://172.17.0.1:9000
```

Caddy also fails with a similar message if the scheme is set to `fastcgi://`

### PR DESCRIPTION
**Pull request by cudevmaxwell**
This allows scheme prefixes "tcp://" and "fastcgi://" in configuration.

Fixes #540

### CODE REVIEW

**Comment by mholt** [comment]
Nice, I like it!

File: middleware/fastcgi/fastcgi.go [hunk 1]
```diff
@@ -128,15 +128,25 @@ func (h Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) (int, error)
 	return h.Next.ServeHTTP(w, r)
 }
 
-func getClient(r *Rule) (*FCGIClient, error) {
-	// check if unix socket or TCP
+// Return the network and address of a given Rule
+func (r Rule) parseAddress() (string, string) {
```
Comment (mholt) [inline middleware/fastcgi/fastcgi.go]: Even though the function is not exported, godoc-style comments should be used just for consistency. i.e. "parseAddress returns the network and address of r."

File: middleware/fastcgi/fastcgi.go [hunk 2]
```diff
@@ -128,15 +128,25 @@ func (h Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) (int, error)
...
+	// check if address has tcp scheme explicitly set
+	if strings.HasPrefix(r.Address, "tcp://") {
+		return "tcp", r.Address[len("tcp://"):]
+	}
+	// check if address has fastcgi scheme explicity set
+	if strings.HasPrefix(r.Address, "fastcgi://") {
+		return "tcp", r.Address[len("fastcgi://"):]
+	}
```
Comment (mholt) [inline middleware/fastcgi/fastcgi.go]: One of these comments (L133 maybe) should probably allude to issue 540 so readers scratching their heads about why it's there can refer to why it was added (since, I think, this is an uncommon way to specify an address)

**Comment by cudevmaxwell** [comment]
Good suggestions from @mholt, added more documentation and made the call to Dial() with `network` and `address` more explicit.

File: middleware/fastcgi/fastcgi.go (hunk 2 above)
Comment (cudevmaxwell) [inline middleware/fastcgi/fastcgi.go]: Expanded the comment a bit, but maybe the reason it was added is needed here? Should I reference the issue directly?

**Comment by abiosoft** [comment]
LGTM :100:

**Comment by mholt** [comment]
Excellent work - thank you!

**Comment by mholt** [comment]
Also, this was the 1,000th commit to master. :smile:
