### PR TITLE
Verify client cert filenames

### LINKED ISSUE #2641: Failed to request client certs with multiple addresses
## 1. Which version of Caddy are you using (`caddy -version`)?

```
Caddy v1.0.0 (h1:KI6RPGih2GFzWRPG8s9clKK28Ns4ZlVMKR/v7mxq6+c=)
```

## 2. What are you trying to do?

Enable client cert verification for multiple addresses.

## 3. What is your Caddyfile?
```text
$ cat Caddyfile

(tls) {
  tls webmaster@namunamu.com {
    dns cloudflare
    clients verify_if_given /etc/certs/ca/certs/ca.crt
  }
}

namunamu.com {
  import tls
}
namunamu.com/var/ {
  import tls
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

```
env CLOUDFLARE_EMAIL=<REDACTED> CLOUDFLARE_API_KEY=<REDACTED> caddy -agree
```

## 5. Please paste any relevant HTTP request(s) here.

skipped

## 6. What did you expect to see?

```
Activating privacy features... done.

Serving HTTPS on port 443
https://namunamu.com
https://namunamu.com/var/


Serving HTTP on port 80
http://namunamu.com
http://namunamu.com/var/
```

## 7. What did you see instead (give full error messages and/or log)?

```
Activating privacy features... done.
incompatible TLS configurations for the same SNI name (namunamu.com) on the same listener: multiple hosts requiring client authentication ambiguously configured
```

## 8. Why is this a bug, and how do you think this should be fixed?

I think the tls config compatibility detector may have flaw in it. I'm not familiar with the code base/architecture so it's just my guess.

## 9. What are you doing to work around the problem in the meantime?

I use a subdomain instead of a path for the particular block. i.e. replace `namunamu.com/var/` with `var.namunamu.com`. But it doesn't solve the problem.

## 10. Please link to any related issues, pull requests, and/or discussion.

This issue (https://github.com/mholt/caddy/issues/2251) may be related, but the situations we stuck with are different.

## Bonus: What do you use Caddy for? Why did you choose Caddy?

Less boilerplate config than nginx - ideal for personal projects!

### PR DESCRIPTION
**Pull request by shouya**
## 1. What does this change do, exactly?

Fix #2641.

## 2. Please link to the relevant issues.

#2641.

## 3. Which documentation changes (if any) need to be made because of this PR?

Nothing I believe.

## 4. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments explaining package types, values, functions, and non-obvious lines of code
- [x] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

File: caddytls/config.go [hunk 1]
```diff
@@ -397,7 +397,7 @@ func assertConfigsCompatible(cfg1, cfg2 *Config) error {
 	if c1.ClientAuth != c2.ClientAuth {
 		return fmt.Errorf("client authentication policy mismatch")
 	}
-	if c1.ClientAuth != tls.NoClientCert && c2.ClientAuth != tls.NoClientCert && c1.ClientCAs != c2.ClientCAs {
+	if c1.ClientAuth != tls.NoClientCert && c2.ClientAuth != tls.NoClientCert && !StringSliceEqual(cfg1.ClientCerts, cfg2.ClientCerts) {
```
Comment (mholt) [inline caddytls/config.go]: This line is getting a little long; let's move the conditions to at least two lines (maybe three).

File: caddytls/config.go [hunk 2]
```diff
@@ -550,6 +550,18 @@ func getPreferredDefaultCiphers() []uint16 {
 	return defaultCiphersNonAESNI
 }
 
+func StringSliceEqual(a, b []string) bool {
```
Comment (mholt) [inline caddytls/config.go]: Unexport this function. Document whether order matters (it does).

**Comment by shouya** [comment]
@mholt: I have adjusted the implementation accordingly and added the test.

File: caddytls/config.go [hunk 3]
```diff
@@ -394,16 +394,9 @@ func assertConfigsCompatible(cfg1, cfg2 *Config) error {
...
 	}
-	if c1.ClientAuth != c2.ClientAuth {
-		return fmt.Errorf("client authentication policy mismatch")
-	}
-	if c1.ClientAuth != tls.NoClientCert && c2.ClientAuth != tls.NoClientCert && c1.ClientCAs != c2.ClientCAs {
-		// Two hosts defined on the same listener are not compatible if they
-		// have ClientAuth enabled, because there's no guarantee beyond the
-		// hostname which config will be used (because SNI only has server name).
-		// To prevent clients from bypassing authentication, require that
-		// ClientAuth be configured in an unambiguous manner.
```
Comment (mholt) [inline caddytls/config.go]: Can you preserve the comment (and update it and move it as needed)? It's a little confusing what is going on in the changes otherwise.

Comment (shouya) [reply caddytls/config.go]: Sure, I'll put it back. To be honest I don't quite get what this comment means here.

Comment (shouya) [reply caddytls/config.go]: Added it back.

Comment (mholt) [reply caddytls/config.go]: I guess it does a bad job of explaining, but basically: if you have two sites defined in the Caddyfile: `example.com/foo` and `example.com/bar`, and one has ClientAuth but the other does not, the expected behavior is ambiguous since we do not know the path at TLS-handshake-time, thus it is possible that a config not requiring client auth would be chosen even if it is needed, which is bad.

Comment (shouya) [reply caddytls/config.go]: @mholt: Thanks for the explanation. It's got more clear with your example!
