### PR TITLE
fix #127

### LINKED ISSUE #127: runtime error: index out of range
I'm getting this PANIC

````
[PANIC /index.php?/api/record/] middleware/fastcgi/fcgiclient.go:386 - runtime error: index out of range
````

 error with super simple redirect:

````
fastcgi / 127.0.0.1:9000 php
rewrite {
        regexp .*
        ext    /
        to     /index.php?/{path}{query}
    }
````

### PR DESCRIPTION
**Pull request by slav123**
fixes issue with Status header coming from php-fpm 5.5 different then regular "HTTP/1.1 200 OK".
If server returns  status code - "200" will be handled properly instead "throwing runtime error: index out of range"

### CODE REVIEW

File: middleware/fastcgi/fcgiclient.go [hunk 1]
```diff
@@ -380,7 +380,10 @@ func (c *FCGIClient) Request(p map[string]string, req io.Reader) (resp *http.Res
 		if err != nil {
 			return
 		}
-		resp.Status = statusParts[1]
+		if (len(statusParts) > 0) {
```
Comment (mholt) [inline middleware/fastcgi/fcgiclient.go]: Parentheses aren't needed here. `if len(statusParts) > 0 {` will suffice.

File: middleware/fastcgi/fcgiclient.go [hunk 2]
```diff
@@ -380,7 +380,10 @@ func (c *FCGIClient) Request(p map[string]string, req io.Reader) (resp *http.Res
 		if err != nil {
 			return
 		}
-		resp.Status = statusParts[1]
+		if len(statusParts) > 0 {
```
Comment (tw4452852) [inline middleware/fastcgi/fcgiclient.go]: I think it should be: `if len(statusParts) > 1`

Comment (slav123) [inline middleware/fastcgi/fcgiclient.go]: nope. > 1 = 2 we are not looking for statusParts[2] - we just need 1

--  
Slawomir Jasinski
e: slav123@gmail.com
    | Quote: "When all else fails read the manual"

Comment (mholt) [inline middleware/fastcgi/fcgiclient.go]: I think Tw's referring to the line below, where you reference `statusParts[1]`. This condition guarantees that `statusParts[0]` exists but not `statusParts[1]`.

Comment (mholt) [inline middleware/fastcgi/fcgiclient.go]: @slav123 Did you have any other questions about this?

Comment (slav123) [inline middleware/fastcgi/fcgiclient.go]: no questions, sorry - was pulled out to other projects. change is already there - **if len(statusParts) > 1** it is

**Comment by mholt** [comment]
Excellent, thank you for the fix!
