### PR TITLE
Fix two import problems: snippets and import literals.

### LINKED ISSUE #2204: snippets don't work across files
### 1. What version of Caddy are you using (`caddy -version`)?
0.10.10

### 2. What are you trying to do?
Define a common snippet then use that in other imported files.

### 3. What is your entire Caddyfile?
`/Caddyfile` (top-level file)
```text
(common) {
  browse
  gzip
}
import apps/*/Caddyfile
```
`/apps/123/Caddyfile`
```text
localhost:9871 {
  import common
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
```text
(✔) aroman-mb ~/tmp $ cat Caddyfile
(common) {
  browse
  gzip
}
import apps/*/Caddyfile
(✔) aroman-mb ~/tmp $ cat apps/123/Caddyfile
localhost:9871 {
  import common
}
(✔) aroman-mb ~/tmp $ caddy
2018/06/15 17:01:36 /Users/aroman/tmp/apps/123/Caddyfile:2 - Error during parsing: File to import not found: /Users/aroman/tmp/apps/123/common
(✘) aroman-mb ~/tmp $
```

### 6. What did you expect to see?
Server starting up.

### 7. What did you see instead (give full error messages and/or log)?
```
2018/06/15 16:59:31 /Users/aroman/tmp/apps/123/Caddyfile:2 - Error during parsing: File to import not found: /Users/aroman/tmp/apps/123/common
```

### PR DESCRIPTION
**Pull request by augustoroman**
Two problems are fixed by this code simplification:
1. Snippets defined in one import file are strangely not available in
   another.
2. If an imported file had a directive with an argument "import", then
   the rest of the tokens on the line would be converted to absolute
   filepaths.

An example of 2 would be the following directive in an imported file:
```
server {
    basicauth / import secret
}
```

In this case, the password would actually be an absolute path to the
file 'secret' (whether or not it exists) in the directory of the imported
Caddyfile.

The problem was the blind token processing to fix import paths in the
imported tokens without considering the context of the 'import' token.

My first inclination was to just add more context (detect 'import' tokens
at the beginning of lines and check the value tokens against defined
snippets), however I eventually realized that we already do all of this
in the parser, so the code was redundant. Instead we just use the current
token's File property when importing. This works fine with imported tokens
since they already have the absolute path to the imported file!

Fixes #2204

### CODE REVIEW

**Comment by mholt** [comment]
Ooo, nice! I'm looking forward to going over these changes. Of course, I invite any other collaborators to give it a review too, since they'll probably be able to sooner than I am.

File: caddyfile/parse_test.go [hunk 1]
```diff
@@ -561,3 +561,81 @@ func TestSnippets(t *testing.T) {
...
+		panic(err)
+	}
+	if err := file.Close(); err != nil {
+		panic(err)
+	}
+	return file.Name()
+}
+
+func TestImportedFilesIgnoreNonDirectiveImportTokens(t *testing.T) {
+	file2 := writeStringToTempFileOrDie(t, `
```
Comment (theodesp) [inline caddyfile/parse_test.go]: Why name it `file2` when you can name it just `fileName` ?

Comment (augustoroman) [reply caddyfile/parse_test.go]: sure, renamed

**Comment by augustoroman** [comment]
ping?  Is this ready to merge?

**Comment by mholt** [comment]
Thanks @augustoroman  -- I love how the solution was basically to delete code and add tests. If you'd like to be a collaborator on the project to help review PRs and issues and get push access, let me know . :)
