### PR TITLE
Very simple fix for #1153

### LINKED ISSUE #1153: Access log defaults to logging post-rewrite URI instead of request URI
### 1. What version of Caddy are you running (`caddy -version`)?

0.9.3

### 2. What are you trying to do?

Log requests to the access log

### 3. What is your entire Caddyfile?
```text
localhost:2020

rewrite {
    to /rewrite.html
}

log access.log
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

`caddy`

### 5. What did you expect to see?

Log entries like:

```
::1 - [30/Sep/2016:10:47:05 -0400] "GET /foo/bar/baz HTTP/1.1" 304 0
::1 - [30/Sep/2016:10:47:05 -0400] "GET /favicon.ico HTTP/1.1" 200 18
```

The output above is from running the same Caddyfile with Caddy 0.8.3.

### 6. What did you see instead (give full error messages and/or log)?

Every log entry shows the rewritten URI:

```
::1 - [30/Sep/2016:10:48:25 -0400] "GET /rewrite.html HTTP/1.1" 304 0
::1 - [30/Sep/2016:10:48:25 -0400] "GET /rewrite.html HTTP/1.1" 200 18
```

This is the output using Caddy 0.9.3.

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Use this simple repo to reproduce: https://github.com/adamwathan/log-rewrite-issue

### PR DESCRIPTION
**Pull request by tobya**
Preventing the deletion of  `Caddy-Rewrite-Original-URI` from header allows php fastcgi apps to correctly log the url requested.

With my basic testing seems to fix #1153 

I do not have enough knowledge to know if the other lines in the if statement are relevant or should also be removed.

### CODE REVIEW

**Comment by mholt** [comment]
Thanks for the PR @tobya! As long as keeping the header there will not impact any upstream PHP applications, then this change should be fine. I'm waiting for at least one reliable confirmation in the linked issue before merging this.

Maybe we could accept this change either way if we skip this header field when forming the env vars that go to the PHP app (in the loop a bit lower with `// Add all HTTP headers to env variables`). That might be the cleanest, surest way to resolve this.

**Comment by tobya** [comment]
I will test it with a lumen php app served by caddy over fastcgi

**Comment by tobya** [comment]
As suggested I ensured that the  Caddy-Rewrite-Original-URI isnt added as a HTTP ENV value passed to fastCGI.

I had to convert both variable to Uppercase before comparison as it turns out the constant is 

> Caddy-Rewrite-Original-URI

but the field value in the Header was actually

>  Caddy-Rewrite-Original-Uri

I thought comparing both uppercase would be more resilent than changing the constant to  Caddy-Rewrite-Original-URI

I am new to GO so let me know if I've broken anything.

**Comment by tobya** [comment]
The change I've made seems to be preventing any ENV variables from being created according to Travis, I don't see how though

**Comment by tobya** [comment]
There is an issue here beyond my issue.

There seems to be a problem with the linter wanting a function to be called 

> blockHTML 

rather than 

> blockHtml

but the blackfriday render is expecting blockHtml

File: caddyhttp/fastcgi/fastcgi.go [hunk 1]
```diff
@@ -246,6 +245,7 @@ func (h Handler) buildEnv(r *http.Request, rule Rule, fpath string) (map[string]
 		env["PATH_TRANSLATED"] = filepath.Join(h.AbsRoot, pathInfo) // Info: http://www.oreilly.com/openbook/cgi/ch02_04.html
 	}
 
+
```
Comment (mholt) [inline caddyhttp/fastcgi/fastcgi.go]: Running `go fmt` will remove these extra empty lines.

File: caddyhttp/fastcgi/fastcgi.go [hunk 2]
```diff
@@ -258,13 +258,19 @@ func (h Handler) buildEnv(r *http.Request, rule Rule, fpath string) (map[string]
...
 	for field, val := range r.Header {
-		header := strings.ToUpper(field)
-		header = headerNameReplacer.Replace(header)
-		env["HTTP_"+header] = strings.Join(val, ", ")
+		
+		if strings.ToUpper(field) != strings.ToUpper(internalRewriteFieldName) {
+		   header := strings.ToUpper(field)
+		   header = headerNameReplacer.Replace(header)
+		   env["HTTP_"+header] = strings.Join(val, ", ")
+		}
```
Comment (mholt) [inline caddyhttp/fastcgi/fastcgi.go]: `go fmt` will fix the indentation here too.

Also, let's do this "fail fast" style, so that instead of indenting all the logic of the loop, we simply do:

```go
if strings.ToLower(field) == strings.ToLower(internalRewriteFieldName) {
    continue
}
...
```

File: caddyhttp/fastcgi/fastcgi.go [hunk 3]
```diff
@@ -258,13 +258,19 @@ func (h Handler) buildEnv(r *http.Request, rule Rule, fpath string) (map[string]
 		env[envVar[0]] = replacer.Replace(envVar[1])
 	}
 
-	// Add all HTTP headers to env variables
+	// Add all HTTP headers (except Caddy-Rewrite-Original-URI ) to env variables
 	for field, val := range r.Header {
-		header := strings.ToUpper(field)
-		header = headerNameReplacer.Replace(header)
-		env["HTTP_"+header] = strings.Join(val, ", ")
+
```
Comment (mholt) [inline caddyhttp/fastcgi/fastcgi.go]: This extra line won't be necessary. Clean code is tidy code. :blush:

File: caddyhttp/fastcgi/fastcgi.go [hunk 4]
```diff
@@ -258,11 +257,16 @@ func (h Handler) buildEnv(r *http.Request, rule Rule, fpath string) (map[string]
 		env[envVar[0]] = replacer.Replace(envVar[1])
 	}
 
-	// Add all HTTP headers to env variables
+	// Add all HTTP headers (except Caddy-Rewrite-Original-URI ) to env variables
 	for field, val := range r.Header {
+
```
Comment (mholt) [inline caddyhttp/fastcgi/fastcgi.go]: Take out this empty line and the one below (269) as well. Thank you!

**Comment by tobya** [comment]
I must admit I'm not sure where to start with writing tests that would do this.    Would I add another request at the bottom of `TestBuildEnv' in fastcgi_test.php?

I also have to admit I'm not sure how to run the test suite (or is that done by travis?).  I'll look at it tomorrow but any pointers would be appreciated, or links to resources.

**Comment by tobya** [comment]
Ok I think I can see how to add a test, however how do I setup the neccessary caddyfile directive to have the rewrite happen?

Is there any docs on setting up and writing tests for caddy?

**Comment by mholt** [comment]
@tobya You found the right place; your test should be in the `TestBuildEnv` test function. All you have to do is add a test case ([like this one, but maybe after it or at the end](https://github.com/mholt/caddy/blob/036633b64a1a769132e3424437e8a7bc4e8bd8ba/caddyhttp/fastcgi/fastcgi_test.go#L259)) where you add a header to the request (try `r.Header.Add()`) with the field name in question with some arbitrary value. Then make sure to set the expected env vars to NOT include that header field, but then check that after the call to buildEnv that the header still exists on the request (`r`). The test should fail without your changes, and pass with them.

**Comment by tobya** [comment]
I have created tests for this PR.  I check that the header still exists and that the ENV variable HTTP_CADDY_REWRITE_ORIGINAL_URI does not.

I had to add a default header value into the call to newReq.  I tested it and it failed without changes and passes with changes.

File: caddyhttp/fastcgi/fastcgi_test.go [hunk 5]
```diff
@@ -293,4 +296,24 @@ func TestBuildEnv(t *testing.T) {
 	envExpected["CUSTOM_URI"] = "custom_uri/fgci_test.php?test=blabla"
 	envExpected["CUSTOM_QUERY"] = "custom=true&test=blabla"
 	testBuildEnv(r, rule, fpath, envExpected)
+
+	// 6. Test Caddy-Rewrite-Original-URI header is not removed
+	const internalRewriteFieldName = "Caddy-Rewrite-Original-URI"
```
Comment (mholt) [inline caddyhttp/fastcgi/fastcgi_test.go]: Instead of redeclaring this here, let's move the const declaration from fastcgi.go out of a function so that this test file can use it too.

Comment (tobya) [inline caddyhttp/fastcgi/fastcgi_test.go]: Caddy-Rewrite-Original-URI is also set as a constant in [rewrite.go](https://github.com/mholt/caddy/blob/bedad34b25cfcc67620fa5b854fed020547efbdf/caddyhttp/rewrite/rewrite.go#L244) using the const name  `headerFieldName`

`internalRewriteFieldName` in fastcgi.go with `headerFieldName` and everything compiles and works, but he test fail as headerFieldName is undefined.  I still get an error even if I add rewrite.go to the import block.

2 Questions
 
  1. Should we use `internalRewriteFieldName` or `headerFieldName`  as the const or create a new const name 
  2. Where should I make the declaration to work in all tests?

**Comment by mholt** [comment]
Hey @tobya, thanks again. You've handled this really well; I'm going to give you collaborator status so you have push privileges to the repo. This way, you can help review pull requests, submit PRs on a branch instead of having to fork, etc. If you accept the invite, please read the [contributing guidelines](https://github.com/mholt/caddy/blob/master/CONTRIBUTING.md) so you know what kind of clean code we expect. :)

**Comment by tobya** [comment]
@mholt Thanks.
